spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/swimpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: swimmer
    password: test1234!
  application:
    name: swimPool
  mustache:
    suffix: .html
    servlet:
      cache: false

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yjh.mymailtest.swimPool


