spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/coffe_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: coffe_user
    password: test1234!
  application:
    name: coffe_crud
  mustache:
    cache: false
    suffix: .html

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yjh.mymailtest.coffe_crud


