spring:
  datasource: # mysql ???
    url: jdbc:mysql://localhost:3306/webcrud_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ??? (MySQL? ??)
    username: webuser  # ?????? ??? ??
    password: test1234!  # ?????? ????
  application:
    name: webcrud

  server:
    port: 8080

  mustache:
    chache: false
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml # /src/main/resources/mapper/**/*.xml ???? xml ??? ????. mapper/abc/*.xml, mapper/dfiek/*.xml, mapper/a/b/c/*.xml ?? ???.
  configuration:
    map-underscore-to-camel-case: true # DB? ???? abc_def ????? abcDef camelCase ????.(Java? ???)
  type-aliases-package: com.yjh.mymailtest.webcrud	# mybatis xml ???? ???? resultType, parameterType, Type? VO, Dto ?? ?? ??????.