# spring.application.name=cinema_jpa
spring:
  application:
    name: food_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    username: food_user
    password: food123@
  mustache:
    suffix: .html
    servlet:
      cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.yjh.bandgroup
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8778
