spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mpacrud_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mpauser
    password: test1234!
  application:
    name: mpacrud

  server:
    port: 8080
  mustache:
    suffix: .html
    enabled: true
    charset: utf-8

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yjh.mymailtest.mpacrud